### ISSUE TITLE
Health multipliers do not behave as expected

### ISSUE THREAD

**Issue by FewerFlaws** [HyperPigeon/Eldritch-Mobs#14]
Assumption: "EliteHealthMod" value multiplies the base health of the mob.
Reality: Modified health is equal to BaseHealth * (2*EliteHealthModifier + 1.2)

Elite, Ultra, and Eldritch modifiers all exhibit the same behavior.  For example, here's the progression in health for zombies and spiders with the following modifiers: Base, Elite (0.9), Ultra (2.4), Eldritch (2.9)

Zombie: 20, 60, 120, 140
Spider: 16, 48, 96, 112

**Comment by HyperPigeon** [comment]
Unfortunately, it's a bit tricky to mess with a mob's max health. The easiest way to increase a mob's max health is to apply a permanent Health Boost effect on them, but this effect is not very precise. 

In the latest release, I've changed the health multiplier to a flat increase via the health boost effect until I can find a more elegant solution.
