### ISSUE TITLE
Piglin Issues

### ISSUE THREAD

**Issue by FewerFlaws** [HyperPigeon/Eldritch-Mobs#15]
1. Piglins are affected by default but piglin brutes are not
2. Eldritch status is lost when a piglin becomes a zombie.

**Comment by HyperPigeon** [comment]
1. Fixed in the latest release
2. Side effect of the way Vanilla Minecraft converts Piglins/Hoglins to their undead versions. Looking for a solution, but not necessarily a pressing concern.
