### ISSUE TITLE
Feature request: Nested modifier list in whitelist

### ISSUE THREAD

**Issue by FewerFlaws** [HyperPigeon/Eldritch-Mobs#18]
I would very much like to configure this so that each mob type has a subset of modifiers available to them.  For example, cloaked spiders are okay, but cloaked creepers are not.  Is this feasible?

**Comment by rxay579** [comment]
Not sure when it got added, but there does appear to be a way to blacklist abilities from specific mobs through a datapack.
https://github.com/HyperPigeon/Eldritch-Mobs/wiki/Blacklisting-abilities-from-being-used-by-specific-mobs

**Comment by HyperPigeon** [comment]
Added w/ rewrite
