### ISSUE TITLE
Webber can overwrite partial blocks the player is standing in

### ISSUE THREAD

**Issue by P03W** [HyperPigeon/Eldritch-Mobs#20]
Ideally it would check for air or water the player was in and only replace those, possibly placing above or slightly to the side if it cant be placed directly ontop

**Comment by CplPibald** [comment]
Had to disable webslinging on my server because of this.  Webs kept destroying half-slab floors even with mobgriefing off.

**Comment by HyperPigeon** [comment]
fixed in latest release
