### ISSUE TITLE
Crash on startup. unclear causes, blame mod blames you.

### ISSUE THREAD

**Issue by LordDecay26** [HyperPigeon/Eldritch-Mobs#25]
here's a pastebin with the crash log in it
https://pastebin.com/KHrC1w8M

**Comment by WardenDrew** [comment]
I'm encountering this as well. Logs: https://gist.github.com/WardenDrew/51c753cf80d9e19827cb04aff80b31ed

**Comment by tenguin** [comment]
I'm encountering this as well now,

This problem started occurring in fabric-api-0.34.0+1.16
This problem does not occur if you stay on fabric-api-0.33.1+1.16, so a change in the Fabric API probably broke the mod.

Thanks for the mod!

**Comment by WardenDrew** [comment]
Based on @tenguin 's info here's the changes to fabric API between those two versions: https://github.com/FabricMC/fabric/compare/0.33.1+1.16...0.34.0+1.16

**Comment by HyperPigeon** [comment]
I'm currently in the process of updating the mod, hopefully, this should fix your issues.

**Comment by HyperPigeon** [comment]
Fixed in the latest release. If you guys run into the same problem, please create another issue.
