### ISSUE TITLE
console logs missing loot tables

### ISSUE THREAD

**Issue by superon** [HyperPigeon/Eldritch-Mobs#26]
https://pastebin.com/bBH21BBw
is this something for a pack dev to complete for fix?

**Comment by HyperPigeon** [comment]
Have you enabled custom loot?

**Comment by superon** [comment]
no, should i?

**Comment by HyperPigeon** [comment]
If you're not using custom loot, then the missing loot tables shouldn't be a problem unless it's causing your game to crash. 

In the future, if you want to use custom loot make sure to fill the custom loot json files.

**Comment by superon** [comment]
i s'pose havin' the console spam that isn't a problem, it just looks ugly to me.   if i make custom loot will this prevent the errors? if so that is what i'll do

**Comment by HyperPigeon** [comment]
Yes, that should stop the console logs from printing.

**Comment by HyperPigeon** [comment]
Fixed in the latest release by adding placeholder loot.
