### ISSUE TITLE
[SUGGESTION] Always Elite/Ultra/Eldritch Configuration

### ISSUE THREAD

**Issue by kirkusmaximus** [HyperPigeon/Eldritch-Mobs#27]
I would like to do things like make sure the Ender Dragon is always Eldritch when spawned. Can I get some datapack config? Preferable would be 3 json files one for each level.

**Comment by HyperPigeon** [comment]
That's a pretty good idea, you should see an update in a day or two.

**Comment by HyperPigeon** [comment]
added in the latest release!

**Comment by kirkusmaximus** [comment]
Thank you!
