### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by Insinfi** [HyperPigeon/Eldritch-Mobs#30]
### **Version**
Eldritch Mobs 1.8.0

### **Description**
We have crash that occure while playing it say it come from eldritch mod so I provide you the crash log I will update with more crash log once I occure again. 

### **Crash logs**
1. [First pastebin 22/06](https://pastebin.com/at75gSYP)

**Comment by HyperPigeon** [comment]
Snatcher has been removed in the latest release, so hopefully, this should fix the issue.
