### ISSUE TITLE
Loot not dropping in latest eldritch  ver for 1.17.1

### ISSUE THREAD

**Issue by itsdinkd** [HyperPigeon/Eldritch-Mobs#38]
So, in creative mode if i summon a eldritch (any tier) loot drops.

in survival, if I summon anything and kill them, no loot drops. 

I tried vanilla mobs, and custom mobs.

**Comment by milkev** [comment]
this happens for me as well, though its not specific to creative/summoning, it just happens randomly and only with the eldritch tier

**Comment by HyperPigeon** [comment]
Hopefully, I fixed this in the latest release. Open up the issue again if it isn't fixed.
