### ISSUE TITLE
Axolotl & Bucket

### ISSUE THREAD

**Issue by Kiryonn** [HyperPigeon/Eldritch-Mobs#39]
So i found a Berserk axolotl in a cave. I had no bucket on me (started the world a few hours before) so i did my best to gather iron and make my bucket. when i finally got him inside the bucket i was really happy. Can you believe an Elite axolotl for the first axolotl encounter ? The rarest species at that !! best friend ever for sure...

Well ... turns out when he got out from the bucket, he returned to 14 max hp, and he was berserk only by name. It was so sad. I even took the time to make him a house just next to mine.

**Comment by Kiryonn** [comment]
dw he is still alive, healthy and lives well in his house.

**Comment by HyperPigeon** [comment]
The issue should be fixed in the latest update. Re-open if you encounter this issue again.
