### ISSUE TITLE
Creeper explosions create unintended potion effects

### ISSUE THREAD

**Issue by ghost** [HyperPigeon/Eldritch-Mobs#41]
Since 16w32a, Creepers with a potion effect will leave a sort of "lingering potion" cloud when they explode that gives players that effect.

When this feature occurs in conjunction with this mod, players are able to have potion effects far greater than should be normally obtained.

To replicate:
- create a new world
- use /summon_elite or similar to spawn a creeper with Resistant or another effect
- put armor on (just in case)
- go into survival and let the creeper blow up
- enter the potion field that is left behind

Versions:
fabric loader: 0.12.5
fabric api: 0.42.1+1.17
eldritch mobs: 1.9.6

Screenshots:
![2021-11-21_17 40 37](https://user-images.githubusercontent.com/94809659/142783791-49ba8745-9013-49f5-803e-912e1a237afd.png)
![2021-11-21_17 40 26](https://user-images.githubusercontent.com/94809659/142783796-dae9390e-7ea8-4966-b6ab-c9ae1d214b16.png)
(the boss bar is still visible after the creeper explodes - but this is a separate issue)

Config:
```
{
	"toggleEldritchBossMobs": false,
	"turnOffNames": false,
	"turnOffBossBars": true,
	"ignoreNamed": true,
	"turnOnGlowingMobs": true,
	"EliteSpawnRates": 1.0,
	"UltraSpawnRates": 1.0,
	"EldritchSpawnRates": 1.0,
	"healthIncrease": true,
	"healthMult": false,
	"EliteHealthMod": 20,
	"UltraHealthMod": 35,
	"EldritchHealthMod": 50,
	"EliteHealthMult": 4.0,
	"UltraHealthMult": 8.0,
	"EldritchHealthMult": 16.0,
	"EliteModTotal": 2,
	"UltraModTotal": 4,
	"EldritchModTotal": 6,
	"EliteExpMult": 10,
	"UltraExpMult": 15,
	"EldritchExpMult": 25,
	"intensity": 1,
	"enableCustomLoot": false,
	"disableModifiers": {
		"disableAlchemist": false,
		"disableBeserk": false,
		"disableYeeter": false,
		"disableBlinding": false,
		"disableBurning": false,
		"disableCloaked": false,
		"disableDeflector": false,
		"disableDraining": false,
		"disableDrowning": false,
		"disableEnder": false,
		"disableGhastly": false,
		"disableGravity": false,
		"disableLethargic": false,
		"disableLifesteal": false,
		"disableOneUp": false,
		"disableRegen": false,
		"disableResistant": false,
		"disableRust": false,
		"disableSpeedster": false,
		"disableSprinter": false,
		"disableStarving": false,
		"disableStormy": false,
		"disableThorny": false,
		"disableToxic": false,
		"disableWeakness": false,
		"disableWebslinging": false,
		"disableWithering": false,
		"disableSniper": false,
		"disableDuplicator": false
	}
}
```

**Comment by ghost** [comment]
Simplest solution would be a config value that just prevents certain types of mobs from spawning as enhanced; for example:
```
disallowedMobs: [
      "minecraft:creeper",
      "somerandommod:mob_that_breaks_things",
      "taterzens:npc"
]
```

Also, I forgot to mention that no other mods besides Eldritch Mobs and Fabric API were used for the above screenshots.

**Comment by HyperPigeon** [comment]
Fixed in the latest release.
