### ISSUE TITLE
1.18.1 startup crash

### ISSUE THREAD

**Issue by MJRamon** [HyperPigeon/Eldritch-Mobs#46]
```
- Replace mod 'Eldritch Mobs' (eldritch_mobs) 1.10.1 with any version that is compatible with: - minecraft 1.18.1

Unmet dependency listing: - Mod 'Eldritch Mobs' (eldritch_mobs) 1.10.1 requires version 1.18 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
```
 

Can you please update mod properties? Thanks!

**Comment by Angular-Angel** [comment]
Have the same thing. Interestingly, this is used in the 'Medieval Minecraft' modpack, which is 1.18.1, so there must be a workaround of some sort... :/

**Comment by bessiq** [comment]
> Have the same thing. Interestingly, this is used in the 'Medieval Minecraft' modpack, which is 1.18.1, so there must be a workaround of some sort... :/

Yeah, you can open the mod .jar file with 7-Zip or something similar, and change the Minecraft version the mod depends on in the `fabric.mod.json` file. In this case, find the `"depends"` section and change the Minecraft version from "1.18" to "1.18.**x**".

Note: 7-Zip opens archive files in a temporary location, so opening it directly and saving it will not update the file in the .jar. I usually just drag the file out of the .jar onto the desktop or something, edit and save it, then drag it back into the 7-Zip window and let it overwrite the old one.

It's kinda hacky and I hate doing it, but in this case it worked. Also, the CurseForge launcher will pretend it doesn't exist, but it's there if you check the mods folder. Hopefully the mod author will push out a proper update soon.

**Comment by MJRamon** [comment]
Yeah, and that is totally legal, cause this mod is under public domain license
https://github.com/HyperPigeon/Eldritch-Mobs/blob/1.18/LICENSE

**Comment by Angular-Angel** [comment]
Okay, that worked! Dead easy, too, cause I'm on Linux and can just edit the file directly in the archive. XD

**Comment by MJRamon** [comment]
[eldritch-mobs-1.10.1.1-1.18.1-UNOFFICIAL.zip](https://github.com/HyperPigeon/Eldritch-Mobs/files/7757986/eldritch-mobs-1.10.1.1-1.18.1-UNOFFICIAL.zip)


I've recompiled mod with actual versions of libs for 1.18.1 and added fixes from this request: https://github.com/HyperPigeon/Eldritch-Mobs/pull/45

By the way, can this mod be server-side only?

**Comment by Angular-Angel** [comment]
Maybe? No way it'll display properly, but it might run that way, if you can convince your modloader it's okay. :/
