### ISSUE TITLE
include your cca bits to avoid users being confused

### ISSUE THREAD

**Issue by Linguardium** [HyperPigeon/Eldritch-Mobs#5]
https://github.com/HyperPigeon/Eldritch-Mobs/blob/f0e27ffccac55d073f5b3ffac2206bef08b67e32/build.gradle#L32

might be a good idea to use include lines also to JiJ these

**Comment by HyperPigeon** [comment]
To clarify, what do you mean by JiJ?

**Comment by Linguardium** [comment]
In addition to the modimplementation line add an include line to jar in jar the cca library
