### ISSUE TITLE
Webslinging mobs are destroying my turtle (from CC:restitched) :cry: 

### ISSUE THREAD

**Issue by FederAndInk** [HyperPigeon/Eldritch-Mobs#51]
I'm using a melee turtle from CC:restitched for an xp farm and when a webslinging mob spawns it replaces my turtle by a cobweb :/
Which is really annoying.

**Comment by FederAndInk** [comment]
should be linked with #20

**Comment by HyperPigeon** [comment]
fixed in latest release
