### ISSUE TITLE
Boss bar function causes lag (addBossbar)

### ISSUE THREAD

**Issue by aria1th** [HyperPigeon/Eldritch-Mobs#52]
https://spark.lucko.me/JQ3zlHgOI0
https://github.com/HyperPigeon/Eldritch-Mobs/blob/2cdc0bb7b79d114bb62d7b067387583627921131/src/main/java/net/hyper_pigeon/eldritch_mobs/mixin/MobEntityMixin.java#L166
![2022-03-31_04 38 36](https://user-images.githubusercontent.com/35677394/160917007-3c1e8da0-0672-4b02-82f4-050bcd5ceed5.png)

**Comment by HyperPigeon** [comment]
extreme lag should be fixed in update to 1.19
