### ISSUE TITLE
Armor stand causing crash in 1.19

### ISSUE THREAD

**Issue by jaredniegas** [HyperPigeon/Eldritch-Mobs#53]
I'm not an expert, but this brings up an armor stand.

[crash-2022-07-24_11.45.41-server.txt](https://github.com/HyperPigeon/Eldritch-Mobs/files/9175074/crash-2022-07-24_11.45.41-server.txt)

**Comment by KlaraChaos** [comment]
can confirm it also causes issues for me

**Comment by HyperPigeon** [comment]
fixed in latest release

**Comment by jaredniegas** [comment]
Thanks Pigeon!
