### ISSUE TITLE
1.12.0 Backport to 1.18.2

### ISSUE THREAD

**Issue by itsdinkd** [HyperPigeon/Eldritch-Mobs#54]
Hello, i am the creator of Another Quality Modpack 2. I as most as other large modpacks on 1.18.2 will be on 1.18.2 for quite some time. This being said, I am writing this in hopes to receive a backport of the latest eldritch update on 1.19 to 1.18.2

Thanks!

**Comment by HyperPigeon** [comment]
Backported to 1.18.2. I did this pretty quickly so there may have been some bugs I overlooked. Let me know if you run into any issues.
