### ISSUE TITLE
[1.19] Incompatibility with RpgDifficulty

### ISSUE THREAD

**Issue by DracoExE** [HyperPigeon/Eldritch-Mobs#55]
I tried to use this mod with RpgDifficulty but the game crashes when launching. I used both mods together in 1.18.1 before without any issues, so it would be great to see if there's a fix for this version too.

MC Version: 1.19
Fabric loader: 0.14.8
Mods used:
- Cloth Config 7.0.73
- Eldritch Mobs 1.12.1
- Fabric Api 0.57.0
- Modmenu 4.03
- RpgDifficulty 1.2.0

Here's the log I'm getting after the crash.
[latest.log](https://github.com/HyperPigeon/Eldritch-Mobs/files/9176149/latest.log)

(Since I'm not sure which mod is causing the issue, I also posted this issue in the RpgDifficulty github)
Thanks!

**Comment by HyperPigeon** [comment]
fixed in latest release
