### ISSUE TITLE
[Suggestion] Generic mob names & special boss bars

### ISSUE THREAD

**Issue by DracoExE** [HyperPigeon/Eldritch-Mobs#56]
If possible, add an option to use generic names to eldritch mobs, such as an elite mob only show as "Elite Zombie" instead of "Burning Blinding Cloaked Zombie" (or "Ultra Zombie" and "Eldritch Zombie" for the other categories)

Another suggestion that could help to determine the type of an eldritch mob can be by using custom colors and/or symbols to the nameplate and the boss bars. For example, Yellow for Elite, Red for Ultra, and Purple for Eldritch, and adding a Star or other symbol at the beginning and the end of the mob name (eg: 1 star for Elite, 2 for Ultra and three for Eldritch)

Keep up the great work!

**Comment by HyperPigeon** [comment]
Added in the latest update.
