### ISSUE TITLE
[1.18.2] Instant Tiered Mobs via Spawners

### ISSUE THREAD

**Issue by itsdinkd** [HyperPigeon/Eldritch-Mobs#58]
v; eldritch-mobs-1.11.3

Putting down a spawner / spawners in world have instantly spawned Eldritch Mobs on each spawn. it seems the chance is not working. 

(settings are; Elite: 1.3, Ultra: 1.2, Eldritch: 1.1)

![image](https://user-images.githubusercontent.com/35115304/181109496-32cf23b6-fe19-401a-af8b-ec5a4710a4b1.png)
(all zombies are eldritch)

**Comment by itsdinkd** [comment]
This is true for any mob in a spawner that is not blacklisted.

**Comment by itsdinkd** [comment]
upon searching for mobs naturally spawned, it looks like **all** whitelisted mobs are automatically eldritch mobs.

![image](https://user-images.githubusercontent.com/35115304/181109880-0d921a01-fd1e-43d3-88c4-fbdea1c3d454.png)

**Comment by itsdinkd** [comment]
Also is there any way you can add a feature to disable eldritch from converting in spawners?

**Comment by HyperPigeon** [comment]
Did you manually set the spawn rate to Elite: 1.3, Ultra: 1.2, Eldritch: 1.1? If so, that means that Elites have a 130% to spawn, Ultras have a 120% chance to spawn, and Eldritchs have a 110% to spawn.

**Comment by itsdinkd** [comment]
Yes, that is how i configured it on the version before the 1.19 backport and it worked fine. 

What should they be? drop the float?

**Comment by HyperPigeon** [comment]
I changed spawn rates to use proportions. For example:
1 -> 100% to spawn
0.50 -> 50% to spawn
0.25 -> 25% to spawn

And so on. For you, I think you would want to set the spawn rate to 0.013, 0.012, and 0.01 for Elite, Ultra, and Eldritch Mobs respectively.

**Comment by itsdinkd** [comment]
Thanks!
