### ISSUE TITLE
Add config to disable for specific mob types

### ISSUE THREAD

**Issue by barrydunne** [HyperPigeon/Eldritch-Mobs#64]
Similar to [Add a config to ignore named entities #4](https://github.com/HyperPigeon/Eldritch-Mobs/issues/4) it would be good to be able to disable this for specified mob types without naming them. In my case I would like to disable for endermen to keep the endermite alive in my xp farm. Thanks.

**Comment by HyperPigeon** [comment]
This feature is already present in Eldritch Mobs: https://github.com/HyperPigeon/Eldritch-Mobs/wiki/Allowing-or-Blacklisting-Entity-Types.
