### ISSUE TITLE
Tag support for always_eldritch,ultra,elite

### ISSUE THREAD

**Issue by itsdinkd** [HyperPigeon/Eldritch-Mobs#65]
Looks like on the update that changed the system it no longer uses the 'always_allowed' tag name, and instead it was changed to 'allowed' and 'blacklist', dropping always. 

I checked the datapack within the latest update of eldritch and I am not seeing anything for making mobs always eldritch ultra elite etc etc like the old version. is this not supported via tags anymore?

**Comment by HyperPigeon** [comment]
It is still supported, I just forgot to add the always_elite, always_ultra, and always_eldritch files to the datapack. I'll add that in the next release today.

**Comment by HyperPigeon** [comment]
Added in the latest release.
