### ISSUE TITLE
[1.18.2] Client crash Eldritch mob

### ISSUE THREAD

**Issue by Seceroth** [HyperPigeon/Eldritch-Mobs#66]
A Mimic from the mod Artifacts became an Eldritch type mob, and upon engaging it, the client crashes.

Fabric Loader 0.14.8
Fabric API 0.57.0+1.18.2
Eldritch Mobs v1.11.0
Artifacts v7.0.3

[crash-2022-09-02_18.06.26-client.txt](https://github.com/HyperPigeon/Eldritch-Mobs/files/9479535/crash-2022-09-02_18.06.26-client.txt)

**Comment by HyperPigeon** [comment]
Have you tried using the latest version of the mod for 1.18.2?

**Comment by Seceroth** [comment]
Have not been able to update the server yet to the newer version. I've removed the entity in the mean time. Will report back if it ever happens again on the new version. I assume it's expected to fix this so I'll close it for now.
