### ISSUE TITLE
1.19.x  zh_cn 中文翻译汉化文件 please confirm completeness and correctnbess @MTSKING BY Silent_lamb 

### ISSUE THREAD

**Issue by MTSKING** [HyperPigeon/Eldritch-Mobs#67]

**Comment by MTSKING** [comment]
[【批量下载】zh_cn等.zip](https://github.com/HyperPigeon/Eldritch-Mobs/files/9502253/zh_cn.zip)


这是预览图片以及
zh_cn.json

**Comment by MTSKING** [comment]
[eldritch_mobs.zip](https://github.com/HyperPigeon/Eldritch-Mobs/files/9503352/eldritch_mobs.zip)

server config 部分汉化 for eaxmple name

**Comment by Gaia9527** [comment]
@Hotaru snowy has submitted a PR, and I have updated the latest Chinese text

**Comment by Gaia9527** [comment]
@Hotaru snowy has submitted a pr. I have updated the latest Chinese text and corrected 2 errors. Thanks for your help

**Comment by Gaia9527** [comment]
@Hotaru-Snowy has submitted a pr. I have updated the latest Chinese text and corrected 2 errors. Thanks for your help

**Comment by Hotaru-Snowy** [comment]
i am sorry for that i didnt see the issue and submitted a pr.

**Comment by Touch-Night** [comment]
But why don't you submit a pr containing all your change to zh_cn.json and eldritch_mobs.json?
