### ISSUE TITLE
uncompatibility with universal enchantments

### ISSUE THREAD

**Issue by jarocajavi** [HyperPigeon/Eldritch-Mobs#74]
Since i updated this mod doesn¡t work with Universal Enchantments. Downgrade to 1.12.8 and works

https://github.com/Fuzss/universalenchants/issues/29

**Comment by Patbox** [comment]
Both server translation api and universalenchantments try to change language providers. Which ends up looping them. This could be solved by universalenchantments  changing their mixin from wrapping vanilla to injecting into it

**Comment by Patbox** [comment]
Resolved by other mod
