### ISSUE TITLE
Axolotls are affected by the mod

### ISSUE THREAD

**Issue by Dekamir** [HyperPigeon/Eldritch-Mobs#75]
Axolotls are affected by the mod, which can easily be cheesed for loot.
They can also be captured with a bucket, making it easier.

**Comment by HyperPigeon** [comment]
This can be easily fixed by removing axolotls from `allowed.json`
https://github.com/HyperPigeon/Eldritch-Mobs/wiki/Allowing-or-Blacklisting-Mobs
