### ISSUE TITLE
Does it support customizing creatures in other mods?

### ISSUE THREAD

**Issue by wsxiya** [HyperPigeon/Eldritch-Mobs#82]

**Comment by HyperPigeon** [comment]
Yes! The mob does support customizing creatures in other mods. Please check out the wiki, it should tell you how to customize non-vanilla mobs!

https://github.com/HyperPigeon/Eldritch-Mobs/wiki

**Comment by wsxiya** [comment]
Thank you, I have learned how to customize creatures
