### ISSUE TITLE
Crash when player sees entity

### ISSUE THREAD

**Issue by itsdinkd** [HyperPigeon/Eldritch-Mobs#83]
When a player visits Limbo from DimDoors, the server stalls and crashes. it looks like there is a eldritch mob there persistenting and causing issues.

https://gist.github.com/itsdinkd/80f1479657fe27f1a321ef91a74cd133

**Comment by HyperPigeon** [comment]
@itsdinkd Did the latest update alleviate the issue? Eldritch Mobs should use up much less server tick now.

**Comment by itsdinkd** [comment]
I havent had any issues since so i think we're good
