### ISSUE TITLE
[SUGGESTION] config option to blacklist certain entities

### ISSUE THREAD

**Issue by TheRealIceCracker** [HyperPigeon/Eldritch-Mobs#84]
Would be nice to be able to blacklist entities from the system, both to prevent rare, powerful spawns from certain mods from becoming unkillable death machines, but also to prevent loot farming of lesser spawns.

The specific issue I am encountering is that each of the size tiers of vanilla Slimes below the large slime are allowed to become elite, etc. and then are easily killed (because multiplying their pitiful base HP still results in very low HP) and drop loot as if they were something actually challenging. It's become a pretty substantial balance issue for me because the elite+ versions of other mobs are very tough and very rewarding with my current config settings.

**Comment by HyperPigeon** [comment]
https://github.com/HyperPigeon/Eldritch-Mobs/wiki/Allowing-or-Blacklisting-Mobs#adding-an-entity-type-to-the-group-of-blacklisted-entities

**Comment by TheRealIceCracker** [comment]
Well that's embarrassing for me idk how I missed it, thanks and sorry!
