### ISSUE TITLE
Custom Abilities get duplicated by /reload

### ISSUE THREAD

**Issue by jozzo402** [HyperPigeon/Eldritch-Mobs#85]
I have a custom ability called "Haunting" that I noticed was being applied to mobs multiple times (eg. Haunting Speedster Rust Haunting Zombie). The ability would also activate twice, so it's not just a visual bug. This behavior stopped when I restarted the game, but would start again whenever I used /reload

1. Create a custom ability via datapack
2. While in-game use /reload any amount of times
3. Use /summon_eldritch etc to spawn a mob with abilities, repeat until you get a mob with multiple instances of the custom ability
4. Restart your game to fix

My haunting.json ability, just in case it's relevant:
```
{
	"name": "Haunting",
	"type": "ACTIVE",
	"subtype": "OFFENSIVE",
	"activationType": "hasTarget",
	"cooldown": 500,
	"command": "execute at {target} run summon bewitchment:ghost ~ ~ ~"
}
```

**Comment by HyperPigeon** [comment]
Fixed in latest release.
