### ISSUE TITLE
Custom Ability "onDamage" trigger doesn't execute properly when using {self} selector in command

### ISSUE THREAD

**Issue by jozzo402** [HyperPigeon/Eldritch-Mobs#86]
Specifically this only happens when using the {self} selector as part of the command. When a command without {self} is used, the command triggers properly from all damage sources.
Commands with a {self} selector do still trigger correctly if the mob takes damage from the environment, such as fall damage, fire, etc.

Examples:
- Will trigger from any damage, including player-dealt damage (working correctly):
```
{
	"name": "Ouch1",
	"type": "PASSIVE",
	"subtype": "OFFENSIVE",
	"activationType": "onDamage",
	"command": "me says Ouch!"
}
```
- Will trigger from environmental damage, but NOT player-dealt damage (not working correctly):
```
{
	"name": "Ouch2",
	"type": "PASSIVE",
	"subtype": "OFFENSIVE",
	"activationType": "onDamage",
	"command": "execute as {self} run me says Ouch!"
}
```

This isn't an issue with only `execute as {self}`, using `effect give {self} ...` results in the same behavior, whereas when I use `effect give My_Username ...` it works correctly. It seems to be an issue with using selectors in the command.

**Comment by HyperPigeon** [comment]
Fixed in latest release
